frontend:
  image: my-frontend-image
  tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  imagePullSecrets:
    - name: nexus-registry
  backendUrl: 'http://backend-service'

backend:
  image: my-backend-image
  tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  imagePullSecrets:
    - name: nexus-registry

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific