concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner1"
  url = "http://gitlab-web"
  id = 4
  token = "t1_zMtz4p3F3Hmz_5kFGqDu"
  token_obtained_at = 2025-03-07T17:17:26Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    pull_policy = ["if-not-present"]
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    environment = ["DOCKER_HOST=tcp://localhost:2375"]
    shm_size = 0
    network_mtu = 0
